# -*- coding: utf-8 -*-
# Calibre-Web Automated – fork of Calibre-Web
# Copyright (C) 2018-2026 Calibre-Web contributors
# Copyright (C) 2024-2026 Calibre-Web Automated contributors
# SPDX-License-Identifier: GPL-3.0-or-later
# See CONTRIBUTORS for full list of authors.

# SPDX-License-Identifier: GPL-3.0-or-later
"""Extraction anchors for SPA-only translatable strings.

The React SPA's English source strings ARE the gettext msgids (see
cps/api/i18n.py — the per-locale JSON catalog is derived from the same .po files
the classic UI uses). But pybabel only scans Python + Jinja (babel.cfg), so a
string that appears ONLY in the .tsx SPA is dropped from messages.pot on the
next re-extract — and msgmerge then marks its translations obsolete, so the SPA
silently falls back to English (this is exactly how #577's "Read now" → "Nu
lezen" was lost after the auto-translation job ran).

Referencing those SPA-only msgids here, with the gettext marker, keeps them in
the catalog across re-extracts. This module is never imported and does nothing at
runtime — babel reads the *source*, not the call result; ``_`` is a local no-op,
not flask_babel's request-scoped gettext (which can't run at import time).

Add a SPA-only msgid here the moment you introduce it in the frontend.
"""


def _(message):  # noqa: E743 - intentional gettext extraction marker, not the builtin
    return message


# #577 — the new-UI "open the reader" button. A distinct msgid from the "Read"
# read-status label (which is a past participle in many languages, e.g. nl
# "Gelezen") so the verb and the status can be translated separately.
_("Read now")

# #573 — the new-UI series view's series-order sort options (Catalog.tsx). Only
# shown when viewing a single series, so the reader can order by position.
_("Series order")
_("Series order (reverse)")

# #572 — inline tag add/remove on the book detail page (quick-edit, no full
# editor). SPA-only strings, anchored so the auto-translation job keeps them.
_("Add tag")
_("New tag")
_("Remove tag")
# NB: the SPA's interpolate() uses {brace} placeholders, not gettext %(name)s —
# a %()s msgid renders its placeholder literally (was a latent bug here + in
# BulkBar). Keep SPA msgids on the {brace} form.
_("Remove tag {name}")

# Book detail completeness pass — star rating (parity with the classic detail
# page) and the "More by this author" browse strip that fills the page for
# sparse books. SPA-only strings (BookDetail.tsx / StarRating.tsx /
# MoreByAuthor.tsx), anchored so the auto-translation job keeps them.
_("Rated {rating} out of 5")
_("More by {name}")

# Bulk-selection toolbar (BulkBar.tsx) — previously unanchored AND written with
# %(n)s, so they were dropped on re-extract and rendered the placeholder
# literally in a visible confirm dialog + button. Anchored on the {brace} form.
_("Merge {n} books into the first selected? The others are removed after their formats are copied over.")
_("Apply to {n} books")


# ============================================================================
# Accessibility remediation (WCAG 2.2 AA sweep) — SPA-only strings introduced by
# the a11y pass: skip link, live-region announcements, ARIA labels for icon-only
# controls, reader/annotation color names, form/error messages. Anchored so the
# auto-translation job keeps them (babel does not scan .tsx).
# ============================================================================
_('Add a format')
_('Add rule')
_('Add to shelf')
_('Add your own')
_('App password label')
_('App passwords')
_('Author')
_('Authors (separate with &)')
_('Back to book')
_('Back to sign in')
_('Blue')
_('Book content')
_('Browse')
_('Change password')
_('Close')
_('Close menu')
_('Contents')
_('Convert failed.')
_('Convert to format')
_('Copy')
_('Could not change password.')
_('Could not create.')
_('Could not fetch cover.')
_('Could not load metadata.')
_('Could not load the book file ({status})')
_('Could not load your account.')
_('Could not save.')
_('Cover')
_('Cover image URL')
_('Cover update failed.')
_('Cover updated.')
_('Create smart shelf')
_('Create your account')
_('Dark')
_('Dark theme')
_('Delete')
_('Delete the {fmt} file? The book stays; only this format is removed.')
_('Delete {fmt}')
_('Delete {n} book(s)? This cannot be undone.')
_('Description contains')
_('Deselect {title}')
_('Edit metadata')
_('Edit {title}')
_('Failed to load books.')
_('Failed to open the book.')
_('Generate')
_('Green')
_('Help')
_('Highlight color')
_('Import from Kobo')
_('Interface language')
_('Invalid username or password.')
# #701 — UI font preset picker (Account page + lib/fonts.ts)
_('UI body font')
_('UI display font')
_('Default (Optima / Sans-Serif)')
_('Default (Bookish Serif)')
_('System Sans-Serif')
_('Bookish Serif')
_('Monospace')
_('Label (e.g. KOReader on phone)')
_('Languages (comma separated)')
_('Light')
_('Light theme')
_('Login failed.')
_('Mark read')
_('Mark unread')
_('Merge')
_('Metadata applied to {n} book(s).')
_('New password for “{label}” — copy it now, it won’t be shown again:')
_('New passwords do not match.')
_('No books here.')
_('No results for "{q}".')
_('No {filter} books here.')
_('Password changed.')
_('Paste URL')
_('Private shelf')
_('Profile')
_('Profile saved.')
_('Public shelf')
_('Publisher')
_('Publishers (comma separated)')
_('Read')
_('Reading progress')
_('Red')
_('Registration failed.')
_('Remove {name}')
_('Request failed.')
_('Reset')
_('Reset your password')
_('Revoke {label}')
_('Save changes')
_('Save failed.')
_('Save profile')
_('Saved.')
_('Saving…')
_('Search')
_('Search failed.')
_('Search for metadata')
_('Search results')
_('Search the library')
_('Select {title}')
_('Sepia')
_('Sepia theme')
_('Series')
_('Series position {n}')
_('Sign in')
_('Sign in failed. Please try again.')
_('Skip to content')
_('Some fields could not be saved.')
_('Table of contents')
_('Tags (comma separated)')
_('Title')
_('Unread')
_('Update password')
_('Upload')
_('Upload failed.')
_('Upload image')
_('Uploading…')
_('Yellow')
_('e.g. MOBI')
_('{format} reader')
_('{name} API key')
_('{n} book(s) added to the shelf.')
_('{n} book(s) deleted.')
_('{n} marked as read.')
_('{n} marked as unread.')
_('{n} selected')
_('{pct}% read')
# "What's new" in-app feature log (SPA /whats-new + the Help menu entry). The
# page CHROME is localized; the per-release entry copy in data/whatsNew.ts is
# English by design (documented on the page). Category names double as the chip
# labels AND the WhatsNewCategory union values — keep them in sync with
# frontend/src/data/whatsNew.ts if that union ever changes.
_("What's new")
_("Help — new updates available")
_("The latest features and fixes in Calibre-Web NextGen — newest first.")
_("{n} update")
_("{n} updates")
_("No release notes yet — check back after the next update.")
_("The interface is translated into your language; these update notes are written in English.")
# Category chips (must match the WhatsNewCategory union)
_("Reading")
_("Library")
_("Sync")
_("Account")
_("Admin")
_("Under the hood")
# "Try it" deep-link button labels (data-authored, but stable enough to anchor
# so a reader's locale can translate the call-to-action).
_("Open your library")
_("Open your shelves")
_("Manage sync & app passwords")
_("Create an app password")
_("Browse series")
_("Open Table view")
_("Open Admin")
_("Open account settings")
_("Browse Discover")
_("Explore your library")
_("Go to Upload")
# Metadata edit — Hardcover editions drill-down (EditBook.tsx)
_("Editions")
_("Back to results")
_("No editions found for this book.")
# Metadata edit — full-record "View all details" overlay (EditBook.tsx)
_("View all details")
_("Result details")
_("Published")
_("Format")
_("Source")
# #585 — in-sidebar "Customize" capsule + inline edit mode (Sidebar.tsx +
# SidebarEditList.tsx): reorder and hide/restore sidebar sections from the new UI.
_("Customize")
_("Customize sidebar")
_("Done")
_("Reset to default")
_("Always shown")
_("Editing sidebar. Reorder or hide sections, then tap Done.")
_("Editing cancelled.")
_("Drag to reorder. Tap ✕ to hide a section. Arrow keys move the focused handle.")
_("Sidebar saved.")
_("Sidebar reset to default.")
_("{label} moved to position {pos} of {total}")
_("Reorder {label} (position {pos} of {total}). Use arrow keys to move.")
_("Delete {label}")
_("Restore {label}")
_("{label} hidden")
_("{label} restored")
_("Could not save sidebar. Please try again.")


# ==== BEGIN AUTOGEN (scripts/extract_spa_strings.py --write) ====
# Auto-anchored SPA-only msgids — every t('literal') in frontend/src that
# is not already anchored above. Do NOT edit by hand; run
#   python scripts/extract_spa_strings.py --write
# after adding or removing SPA strings. The CI gate
# (tests/unit/test_spa_strings_anchored.py) fails if this drifts.
_("(replace cover)")
_("A few random picks from your library")
_("A one-time full duplicate scan is needed. Run it from CWA settings, then return here.")
_("API keys")
_("Account: {name}")
_("Add identifier")
_("Add to favorites")
_("Admin group")
_("Advanced")
_("Advanced search")
_("All shelves")
_("Allow remote (magic-link) login")
_("Allowed groups (comma-separated)")
_("Any")
_("Any format")
_("Any language")
_("Any series")
_("Any tags")
_("Apply selected")
_("Apply to all selected (only filled fields change; replaces existing values):")
_("Applying…")
_("Archive")
_("Archived")
_("Ask in Discord")
_("Authentication")
_("Authentication & security")
_("Authorised — signing you in…")
_("Authorize URL")
_("Authors")
_("Auto-create users")
_("Auto-create users on first login")
_("Back to edit metadata")
_("Back to library")
_("Back to the classic view")
_("Base DN")
_("Book not found.")
_("Books")
_("Books per page")
_("Border fill style")
_("Built-in providers (leave blank to disable):")
_("Bulk actions")
_("CA certificate path")
_("Can upload books")
_("Cancel")
_("Cancel rename")
_("Categories")
_("Certificate file path")
_("Certificate path")
_("Change cover")
_("Checking…")
_("Choose a cover")
_("Choose a cover image to upload")
_("Choose an image…")
_("Choose fields")
_("Clear selection")
_("Client ID")
_("Client secret")
_("Client secret (leave blank to keep)")
_("Close reader")
_("Columns")
_("Configured")
_("Confirm new password")
_("Convert")
_("Convert before sending")
_("Convert from")
_("Copied to clipboard")
_("Copy link")
_("Could not create the shelf.")
_("Could not load candidates.")
_("Could not load duplicates.")
_("Could not load highlights.")
_("Could not load this text file.")
_("Could not read this comic archive.")
_("Could not save the shelf.")
_("Couldn’t start a magic link. Please try again.")
_("Cover locked")
_("Cover not reachable")
_("Cover save failed.")
_("Cover updated from the selected result.")
_("Create")
_("Create account")
_("Create an account")
_("Create shelf and add book")
_("Create user")
_("Creating…")
_("Current")
_("Current cover")
_("Current password")
_("Currently reading")
_("Custom border colour")
_("Default book language")
_("Default interface language")
_("Default roles for new OAuth users:")
_("Defaults live in Admin → Configuration → Kobo sync.")
_("Delete this smart shelf? Your books are not affected.")
_("Description")
_("Disable standard password login")
_("Discover")
_("Dismiss")
_("Dismiss this group")
_("Documentation")
_("Done reordering")
_("Download")
_("Drop files here, or click to choose")
_("Duplicate")
_("Duplicate books")
_("Duplicates")
_("E-reader preview")
_("Each type (isbn, amazon, google, doi…) may appear once.")
_("Edit")
_("Edit smart shelf")
_("Email")
_("Email (SMTP) server")
_("Email (optional)")
_("Email claim")
_("Email me a reset")
_("Email settings saved.")
_("Enable Kobo sync")
_("Encryption")
_("Expires in")
_("Expose only selected shelves over OPDS")
_("Failed to load.")
_("Favorite")
_("Favorited")
_("Fetch")
_("Fetch metadata from web")
_("Files")
_("Files are queued for the library's ingest process and appear once imported.")
_("Forgot password?")
_("Format queued — it will appear once processed.")
_("Formats — exclude")
_("Formats — include")
_("From address")
_("Generate a new link")
_("Give your smart shelf a name.")
_("Go to your library")
_("Group claim")
_("Group members field")
_("Group name")
_("Group object filter")
_("HTML is allowed and sanitized on display.")
_("Header name")
_("Help & support")
_("Help menu")
_("Hide")
_("Hide Discover section")
_("Hide fields")
_("Hide password")
_("Highlight")
_("Highlights")
_("Icon")
_("Identifier type")
_("Identifier value")
_("Identifiers")
_("In your book")
_("In-browser reading currently supports EPUB. Use download or the classic reader for other formats.")
_("Issuer / base URL")
_("It may have moved, or it might still live in the classic interface.")
_("KOReader Progress")
_("Key file path")
_("Key path")
_("Kobo sync on")
_("LDAP")
_("Language")
_("Languages")
_("Languages — include")
_("Larger")
_("Larger text")
_("Library settings")
_("Load more")
_("Loading…")
_("Lock cover")
_("Log in with a magic link")
_("Login")
_("Login button text")
_("Login method")
_("Looks good")
_("Low-res")
_("Magic link QR code")
_("Make private")
_("Make public")
_("Manage admin role from OAuth group")
_("Manage shelves")
_("Mark as read")
_("Mark as unread")
_("Match")
_("Max")
_("Max authors shown")
_("Maximum rating")
_("Member user filter")
_("Metadata URL (OIDC auto-discovery)")
_("Min")
_("Minimum rating")
_("More cover options (search providers, e-reader preview)")
_("More server configuration")
_("Move down")
_("Move up")
_("My account")
_("Name")
_("Need to report an issue? Try the new")
_("New")
_("New password")
_("New shelf name")
_("New shelf name…")
_("New shelf…")
_("New smart shelf")
_("New user")
_("Next page")
_("No books match this smart shelf right now.")
_("No books match those criteria.")
_("No candidates found yet. Try a different search or refresh.")
_("No contents found.")
_("No duplicate groups found.")
_("No excluded tags")
_("No highlights yet. Highlight while reading, or import from a Kobo device.")
_("No pages found in this comic.")
_("No shelves yet — create one below.")
_("No sources need a key.")
_("No tasks running.")
_("None")
_("Not configured")
_("OAuth / OpenID Connect")
_("On another device where you’re already signed in, scan this code or open the link below to authorise this device.")
_("Open classic reader")
_("Open navigation")
_("Open reader")
_("Open the classic interface")
_("Open the link below on your signed-in device.")
_("OpenLDAP server")
_("PDF reader")
_("Password")
_("Password (leave blank to keep)")
_("Pick a cover from any source we support, paste a URL, upload a file, or use the cover embedded in the book itself.")
_("Picked up {label}. Drag to reorder, release to drop.")
_("Port")
_("Preparing your magic link…")
_("Previous page")
_("Progress")
_("Public")
_("Published after")
_("Published before")
_("Publishers")
_("Random books shown")
_("Rating")
_("Rating (stars)")
_("Read status")
_("Read status filter")
_("Recipient(s) — blank = your e-reader email")
_("Redirect host (full URL)")
_("Refresh")
_("Registering…")
_("Remember me")
_("Remove from favorites")
_("Remove from shelf")
_("Remove identifier")
_("Remove rule")
_("Rename")
_("Reorder")
_("Replace cover with this one?")
_("Replace cover?")
_("Report Issue on Discord")
_("Report Issue on GitHub")
_("Require group membership")
_("Reverse-proxy header login")
_("Run time")
_("SMTP server")
_("SSL/TLS")
_("STARTTLS")
_("Save")
_("Save email settings")
_("Save name")
_("Save security settings")
_("Save settings")
_("Saved. Restart the server for the login changes to take effect.")
_("Scopes")
_("Search books")
_("Search title, author…")
_("Searching every source…")
_("Searching…")
_("Security settings saved.")
_("See how each cover looks padded for your device")
_("Select")
_("Select multiple")
_("Send")
_("Send to e-reader")
_("Send-to-eReader email")
_("Sending…")
_("Series index")
_("Series — include")
_("Serve over HTTPS")
_("Server SSL / HTTPS")
_("Server announcement (shown to all users)")
_("Server host")
_("Service account (DN)")
_("Service password")
_("Service password (leave blank to keep)")
_("Set a metadata URL to auto-fill the endpoints below, or enter them manually.")
_("Settings saved.")
_("Shelf name")
_("Shelf not found.")
_("Shelves")
_("Show Discover section")
_("Show books in language")
_("Show e-reader previews on each candidate")
_("Show password")
_("Shuffle picks")
_("Sign in with a magic link")
_("Sign out")
_("Signing in…")
_("Site title")
_("Smaller")
_("Smaller text")
_("Smart shelf not found.")
_("Smart shelves")
_("Some sources need a key for better covers")
_("Something went wrong. Try again.")
_("Sort order")
_("Source details")
_("Statistics")
_("Status")
_("Sync only selected shelves to Kobo")
_("Table view")
_("Tags")
_("Tags — exclude")
_("Tags — include")
_("Target aspect ratio")
_("Task")
_("Tasks")
_("That URL is not a usable image.")
_("Theme")
_("These open the full configuration pages. Changes there apply to the whole server.")
_("This format opens in the full-screen reader.")
_("This magic link expired. Generate a new one to try again.")
_("This page doesn't exist here.")
_("Title, author, or ISBN")
_("Token URL")
_("Trust authentication header")
_("Unarchive")
_("Unhide")
_("Unlock the cover above to apply a new one.")
_("Unlock the cover to change it")
_("Untitled")
_("Upload as cover")
_("Upload books")
_("Use these to connect OPDS readers or KOReader sync without your main password.")
_("Use this cover")
_("User")
_("User administration")
_("User object filter")
_("Userinfo URL")
_("Username")
_("Username claim")
_("Versions")
_("View settings")
_("Waiting for you to authorise…")
_("When locked, fetching metadata will not overwrite this cover.")
_("Your Library")
_("Your browser cannot play this audio format.")
_("Your personal digital library")
_("all rules")
_("any rule")
_("books")
_("books match")
_("copies")
_("e-reader")
_("e.g. Unread sci-fi")
_("eReader email subject")
_("or continue with")
_("shared")
_("to")
_("type (isbn, amazon, doi…)")
_("value")
_("you")
_("{n} found")
_("{ok} of {total} sources answered")
_("…or paste an image URL")
_("← Back to book")
_("← Back to sign in")
_("← Library")
# ==== END AUTOGEN ====
