#!/usr/bin/env python3
# Calibre-Web Automated – fork of Calibre-Web
# Copyright (C) 2018-2026 Calibre-Web contributors
# Copyright (C) 2024-2026 Calibre-Web Automated contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Carry the previous ``POT-Creation-Date`` into a freshly extracted POT.

Why this exists
---------------
``pybabel extract`` stamps ``POT-Creation-Date`` with the wall clock every
time it runs. ``update-translations.yml`` runs it on every push to main, so
the date changes ~99x/month even when not a single msgid moved. ``msgmerge``
then copies the POT header into all 28 locale ``.po`` files and the bot
commits the lot.

That timestamp is what makes community translation PRs rot. gettext emits::

    "POT-Creation-Date: 2026-07-16 02:13+0000\\n"
    "PO-Revision-Date: 2026-07-14 09:12+0300\\n"

Those two lines are ADJACENT with no unchanged line between them. Main touches
the first (bot), the translator's editor touches the second (Poedit stamps it
on save) — different lines, but git cannot split adjacent changed lines into
separate hunks, so the 3-way merge conflicts. Measured on fork PR #938: that
header pair was its ONLY conflict, while ~1345 lines of ``#:`` location churn
in the same file merged cleanly (unchanged msgid lines separate those hunks).

Freezing the date makes main's header byte-stable, so a translator's save
merges cleanly and the PR stays mergeable. This removes the conflict class at
its source instead of re-authoring each contribution by hand — which is what
happened to #718, #820, #844, #895 and #938.

Why freezing is safe
--------------------
Nothing reads this field. It appears in no consumer in this repo,
``msgfmt --check`` passes with the line absent entirely, and gettext resolves
plurals and charset from ``Plural-Forms``/``Content-Type`` in the compiled
``.mo``. It is metadata for humans, and for a catalog regenerated by a bot on
every push it tells a human nothing useful. ``test_pot_creation_date_freeze.py``
pins the no-consumer assumption so a future reader of this field fails loudly
rather than quietly trusting a frozen timestamp.

Only ``POT-Creation-Date`` is touched. Everything else in the fresh POT —
including real msgid changes and ``#:`` references — is left exactly as babel
extracted it.

Usage
-----
    python3 scripts/freeze_pot_creation_date.py <target.pot> <reference.pot>

``target`` is the freshly extracted POT (rewritten in place); ``reference`` is
the previously committed POT snapshotted before extraction. A reference that
is missing or has no ``POT-Creation-Date`` (first-ever extract) is not an
error — the fresh date is simply kept. A missing target IS an error: it means
extraction did not produce what the pipeline expects.

Runs after ``fix_pot_format_flags.py`` and BEFORE the ``msgmerge`` loop in
``scripts/update_translations.sh`` — msgmerge is what fans the POT header out
to every locale, so freezing afterwards would leave all 28 .po files churned.
"""

from __future__ import annotations

import sys
from pathlib import Path


HEADER_PREFIX = '"POT-Creation-Date:'


def read_creation_date(text: str) -> str | None:
    """Return the full ``POT-Creation-Date`` header line, or None if absent."""
    for line in text.splitlines():
        if line.startswith(HEADER_PREFIX):
            return line
    return None


def apply_creation_date(text: str, date_line: str) -> str:
    """Replace the ``POT-Creation-Date`` line in ``text`` with ``date_line``.

    Every other line is preserved byte-for-byte, including the trailing
    newline, so the only diff this can ever produce is the one line.
    """
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.startswith(HEADER_PREFIX):
            newline = "\n" if line.endswith("\n") else ""
            lines[index] = date_line.rstrip("\r\n") + newline
            break
    return "".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(
            "usage: freeze_pot_creation_date.py <target.pot> <reference.pot>",
            file=sys.stderr,
        )
        return 2

    target = Path(argv[0])
    reference = Path(argv[1])

    if not target.is_file():
        print(f"[!] freeze: target POT not found: {target}", file=sys.stderr)
        return 1

    if not reference.is_file():
        print(f"[i] freeze: no previous POT at {reference}; keeping fresh date")
        return 0

    previous = read_creation_date(reference.read_text(encoding="utf-8"))
    if previous is None:
        print("[i] freeze: previous POT has no POT-Creation-Date; keeping fresh date")
        return 0

    current_text = target.read_text(encoding="utf-8")
    current = read_creation_date(current_text)
    if current is None:
        print("[i] freeze: fresh POT has no POT-Creation-Date; nothing to freeze")
        return 0

    if current == previous:
        return 0

    target.write_text(apply_creation_date(current_text, previous), encoding="utf-8")
    print(f"[i] freeze: restored {previous.strip()}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
